version: '3.7'

networks:
    app:
        driver: bridge

services:
    nginx:
        container_name: tochka_nginx
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
          - app
        ports:
            - 80:80
        depends_on:
          - postgres
          - account
        restart: on-failure:3
    postgres:
        build:
            context: ./db
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./db/data/postgres:/var/lib/postgresql/data/pgdata
        ports:
        - 5432:5432
        networks:
        - app
        restart: on-failure:3

    account:
        image: account:latest
        build:
            context: ./src
        networks:
            - app
        environment:
            - DB_HOST
            - DB_NAME
            - DB_USER
            - DB_PASSWORD
            - LOG
        ports:
            - 8080:8080
        restart: on-failure:3
        depends_on:
            - postgres